### ISSUE TITLE
Create MovementRepository

### ISSUE THREAD

**Issue by theprimegamer** [theprimegamer/breakthrough-conflict-online#10]
The goal of this issue is to Read from a .json file and store the results in memory so that we do not need to read the file again unless it changes or gets removed from memory.

- Create a C# Class called MovementRepository.cs in Core/Data/
- Create a public method called GetMovementCost that requires a TerrainType, MovementType, and WeatherType and returns a short representing the cost of movement for MovementType over TerrainType in the current WeatherType.
  - This method will read from the MovementChart.json file, store the contents into an object, and perform a lookup with that object.
- Create a public method called GetMovementCost that requires a TerrainType and MovementType (*No WeatherType*) and returns a short representing the cost of movement for MovementType over TerrainType in 'Clear' WeatherType. This method will be used for the first few iterations of the project to streamline coding.
  - This method should call the first method to reduce repeated code and maximize reuse of code.
- I believe the proper way to store this information is a Dictionary<string, Dictionary<string, Dictionary<string, short>>> where the first string is the WeatherType, second is TerrainType, third is MovementType, and the short is the cost over said terrain
- **Future**: The lookup object should also be stored in some sort of cache so that subsequent calls to GetMovementCost will not read from the file again.
- **Future**: Version the .json file so that we can check if a change has occurred since the last write to cache.

Test: #11

**Comment by m-soup** [comment]
Implementation complete, closing issue.
