### ISSUE TITLE
Create MovementRepositorySpec

### ISSUE THREAD

**Issue by theprimegamer** [theprimegamer/breakthrough-conflict-online#11]
The spec should test:
- First indices and Last indices for all dictionaries
- Four smoke tests of a combination of the three variables to make sure the data is mostly correct.
- There is no need to do a full test of the second method (Without WeatherType) because that method should call the first method which was tested with the above tests. That being said, the second method should have at least three tests run on it to make sure it functions properly.

**Comment by m-soup** [comment]
Implementation complete, closing issue.
