### ISSUE TITLE
Create CacheHelper

### ISSUE THREAD

**Issue by theprimegamer** [theprimegamer/breakthrough-conflict-online#14]
This file will live in Core/Util. It is used to handle the interaction between the system's cache and the application.

The file will define a static class, CacheHelper, that will be called by other parts of Core to interact with the system's cache. It will contain two functions:
- public static bool SetItem(string cacheKey, object cacheValue, BcoCachePolicy bcoCachePolicy = BcoCachePolicy.OneYear)
  - This method has a default parameter for the third parameter that will default the cache to store the cacheValue until the cache is cleared. Other cache policies are defined below. 
  - The method will add an entry to the system's cache with the key cacheKey and the value cacheValue. A policy will be created within the function so that the user developer does not have to worry about it.
- public static T GetItem\<T\>(string cacheKey) 
  - This method has a generic that is used to specify the return type of the function. The generic is useful so the developer does not have to cast after they have received an item from the cache.
  - If this method has no value for cacheKey OR cast fails to the generic, null will be returned

The file will also contain an enum definition for BcoCachePolicy. This enumeration will be used to specify predefined CachePolicy's for the BCO system. The enumeration will be defined as follows:
- Forever: Item stays in cache until cleared
- OneYear: Item stays in cache for one year
- OneDay: Item stays in cache for one day

Test: #15

**Comment by m-soup** [comment]
Implementation complete, closing issue.
