### ISSUE TITLE
Test CacheHelper

### ISSUE THREAD

**Issue by theprimegamer** [theprimegamer/breakthrough-conflict-online#15]
This spec will contain tests that include:
- Setting and getting a cache entry with a value of a string (String)
- Setting and getting a cache entry with a value of a int (Int32)
- Setting and getting a cache entry with a value of a Dictionary
- Setting a cache entry twice and getting the latest value instead of the first value.
- Getting a cache entry that does not exist and expecting a null

*Note:* Testing equality of objects may be more difficult than just using ==

**Comment by m-soup** [comment]
Implementation complete, closing issue.
