### ISSUE TITLE
Create Game Functionality

### ISSUE THREAD

**Issue by theprimegamer** [theprimegamer/breakthrough-conflict-online#20]
# Create Game Functionality
A user needs to have the ability to create a game within the system for other users to play on. The ability to add additional users through an invite system will be implemented later as it is not part of the MVP. This functionality should be part of the GameManager class.

## Detailed Requirements
- Invitees should not contain the user that is creating the Game. It would not make sense to invite yourself. This does not need to throw an error, but it should be remedied without alerting the user.
- Spectators should never contain any invitees. We don't want a player who is playing to be able to spectate the game as well. This should throw an error.
- The game should be in an started state upon creation (For MVP)
- Any `Unit` that is on the `Map` should be owned by `user` (For MVP)
- No invites will be sent out from this method (For MVP)

## Implementation
GameManager.cs: public static Task<ObjectId> GameManager.CreateGame(User user, ObjectId mapId, List<ObjectId> inviteeIds = null, List<ObjectId> spectatorIds = null)
- `user` is the user that creates and owns the new game
   - The `user` should be added to the `Players` array
- `map` is the `Map` that the game will be played on.
   - `map` contains a list of `Unit` that should be copied to the game's `Units` as it is created.
- `invitees` is a list of `ObjectId` that represent Ids of users that will be taking turns within the game. They should be included in the game's `Players` property.
   - If no value is provided, `invitees` will default to null and the only `User` in the `Players` list should be `user`
   - This list should not include `user`. Add a check to **remove** `user` from `invitees` if it exists.
- `spectators` is a list of `PlayerInfo` that have the ability to watch the game. They should be included in the game's `Spectators` property
   - If no value is provided, `spectators` will default to null, and `Spectators` will be null on the created `Game`
  - `spectators` should never include ANY `PlayerInfo` in the `PlayerInfo` array (unique on `Id`). Add a check to assure this. If this check fails (a player is present within spectators), **throw** an `IllegalArgumentException` with a proper message.
- `CurrentPlayer` should default to `user` (For MVP)
- `CreateGame` returns the `ObjectId` of the newly created `Game`.

## Tests
- Happy Path
- Creation of a game with just the first two parameters
- Creation of a game with an invitee
- Creation of a game with two invitees, one of which is `user`.  Players should have a Count of 2.
- Creation of a game with no invitees and a spectator
- Creation of a game with no invitees and a spectator that is `user`. This should throw an error.

**Comment by m-soup** [comment]
Closing issue.
