### ISSUE TITLE
Move Unit in Game Functionality

### ISSUE THREAD

**Issue by theprimegamer** [theprimegamer/breakthrough-conflict-online#26]
# Move Unit Functionality
A user needs to have the ability to move a unit around the map. This will be the basis for the Move command in the application. For MVP, we are ignoring Fuel functionality.

## Detailed Requirements
- A unit cannot be moved outside of the bounds of the map
- A unit cannot move on top of another unit. The "Join" functionality #27 will be implemented later
- Fuel and subsequently Terrain Cost will be ignored (For MVP)
- A unit may only be moved by the owner

## Implementation
public static Task<ObjectId> GameManager.MoveUnit(Game game, Unit unit, Location location, User user)
- `game` is the game that is being modified
- `unit` is the unit that is being moved
- `location` is the location on the map where the unit is being moved.
  - We will not be checking terrain cost or fuel for MVP
  - If `location` is out of out bounds of the `map` on the `game` then throw an
 `ArgumentOutOfBoundsException`
  - Check to make sure `location` is within the `unit` movement range using the Map's `GetLocationWithinRange` function. If not, throw an `ArgumentOutOfBoundsException` 
- `user` is the user executing the command
  - If user does not own the unit being moved, throw an `InvalidArgumentException`
- Make sure a unit is not occupying the Location that is being moved to. If one is already there, throw an `InvalidArgumentException`

## Tests
- Happy Path
- Make sure unit is within the game's map's bounds
- Test to make sure only the owner can move the unit
- Make sure the location being moved to is not occupied by another unit in the game #

**Comment by m-soup** [comment]
Issue has been closed.
