### ISSUE TITLE
Refactor GameManager to use new Repository structure

### ISSUE THREAD

**Issue by theprimegamer** [theprimegamer/breakthrough-conflict-online#37]
Like the UserManager, the GameManager needs to be changed to use the DbRepository instead of accessing  the database directly.

Use UserManager as an example

**Comment by theprimegamer** [comment]
@m-soup I think you're working on this. If that is the case, can you assign this to yourself and move it over in the Projects section of github?

**Comment by m-soup** [comment]
Closing implemented issue.
