### ISSUE TITLE
Create TerrainStarRepository

### ISSUE THREAD

**Issue by theprimegamer** [theprimegamer/breakthrough-conflict-online#4]
The goal of this issue is to Read from a .json file and store the results in memory so that we do not need to read the file again unless it changes or gets removed from memory.

- Create a C# Class called TerrainStarRepository.cs in Core/Data/
- Create a public method called GetTerrainStars that requires a TerrainType and returns a short of the number of Terrain Stars for the given TerrainType.
  - This method will read from the TerrainStarChart.json file, store the contents into a dictionary, then perform a lookup with that dictionary.
- **Future**: The dictionary should also be stored in some sort of cache so that subsequent calls to GetTerrainStars will not read from the file again.
- **Future**: Version the .json file so that we can check if a change has occurred since the last write to cache.

Test: #5

**Comment by m-soup** [comment]
Implementation complete, closing issue.
