### ISSUE TITLE
Create Tests Util (CreateFakeX)

### ISSUE THREAD

**Issue by theprimegamer** [theprimegamer/breakthrough-conflict-online#40]
As a developer, I want an easy way to create fake objects across test classes without having to write duplicate code.

Create a util folder within the Tests project. This folder will contain one file called TestsUtil.cs. This file will house static methods for CreateFake<Entity> where <Entity> is an object in the system (e.g. User, Map, Terrain, Unit, etc.). These methods will be used within the Spec classes to create fake objects to test with while using mocked repositories.

**Comment by m-soup** [comment]
Closing implemented issue.
