### ISSUE TITLE
TerrainStarRepositorySpec

### ISSUE THREAD

**Issue by theprimegamer** [theprimegamer/breakthrough-conflict-online#5]
This spec should test:
- First Index
- Last Index
- Two Indexes within bounds
- *Out of Bounds is not possible because the GetTerrainStars function only allows TerrainTypes as input*
- Include a test that checks to see if the .json file is read multiple times after subsequent calls. This may involve adding a new variable to the Repository to keep track of reads.

**Comment by theprimegamer** [comment]
Depends on #4

**Comment by m-soup** [comment]
Implementation complete, closing issue.
