### ISSUE TITLE
Create DamageRepository

### ISSUE THREAD

**Issue by theprimegamer** [theprimegamer/breakthrough-conflict-online#8]
The goal of this issue is to Read from a .json file and store the results in memory so that we do not need to read the file again unless it changes or gets removed from memory.

- Create a C# Class called DamageRepository.cs in Core/Data/
- Create a public method called GetDamage that requires two UnitTypes (attacking and defending) and returns a double representing the damage (in percent) that the attacking unit will deal to the defending unit.
  - This method will read from the DamageChart.json file, store the contents into an object, and perform a lookup with that object.
- I believe the proper way to store this information is in a Dictionary<string, Dictionary<string, double>>. The first string is the attacking unit type, the second string is the defending unit type and the double is the damage dealt (in percent)
- **Future**: The lookup object should also be stored in some sort of cache so that subsequent calls to GetDamage will not read from the file again.
- **Future**: Version the .json file so that we can check if a change has occurred since the last write to cache.

Test: #9

**Comment by m-soup** [comment]
Implementation complete, closing issue.
